### ISSUE TITLE
NoException Checkstyle Project Regression

### ISSUE THREAD

**Issue by rnveach** [checkstyle/regression-tool#15]
We need to consider running the snapshot version of the jar against the real Checkstyle project as a final test to make sure any new changes work without throwing an exception.

The question is what commit should we run against? Only the latest one or the top X? Should we create our own commit to test some basic avenues?

Reports shouldn't be uploaded, regardless.

This is completely separate from the junits.

This is blocked by default module testing.

These regression(s) will also showcase to Checkstyle project how to use our utility and incorporate it into their process.

**Comment by rnveach** [comment]
@Luolc Please come up with a way to attach our tool to checkstyle in travis' CI.
There is no documentation, so this is the only way others will know how to use our utility without viewing the source.

**Comment by Luolc** [comment]
@rnveach Got it. I would create a issue for documentation and write it at meantime.

**Comment by Luolc** [comment]
@rnveach 
I think I may need to enable Travis-CI on my fork of checkstyle project and test this on it. What's your opinion? This could avoid bothering the dev on checkstyle project, but maybe not convenient for reviewing.

**Comment by rnveach** [comment]
@Luolc Feel free to create your own travis. I do this too in checkstyle.

We still need this in our CI here before we incorporate it in any external place like checkstyle.

**Comment by rnveach** [comment]
Fix was merged.
