### ISSUE TITLE
Refine DiffParserTest

### ISSUE THREAD

**Issue by Luolc** [checkstyle/regression-tool#18]
Taken from https://github.com/checkstyle/regression-tool/pull/17#pullrequestreview-42994141

- We should include all types of differences in git.
New file, removed file, renamed file, moved file, chmod change (linux only).
- We should also add a test where PR branch is behind master. This happens quite a bit when people don't stay up to date with changes in master.
We should still correctly identify PR branch commits in this scenario and only get it's differences.
- We also need a test where PR branch has multiple commits on master.

**Comment by rnveach** [comment]
This should be done before or right after Issue #15 as we want this utility very well tested before we give it to Checkstyle for actual usage.
Tests will show if our code works correctly for the strange cases we will find in real usage.

**Comment by rnveach** [comment]
Message from Luolc (connectivity issues):
> For `PR branch is behind master`:
> I did some investigation on issue 18 today. When master is latest and PR doesn't rebase latest code, there would be diff that we don't expect. Git CLI has the same behavior, so we have to find a workaround to handle not latest PR. I don't know if we could do this without rebase currently. I will keep investigating.

**Comment by Luolc** [comment]
The git CLI has the same behavior. So it is a feature of git to show the diff of un-rebased files. While in GitHub "File Changed" tab, unrelated files won't appear. So it is sure to have a way to avoid this. At least we could run rebase command for it, but it should be the last solution.

**Comment by Luolc** [comment]
I find a command `git diff master...<branch>` can fit our need, but I don't know how to implement this in JGit yet.

Here is an example to see how it works:
```bash
$ git init
$ 
$ echo HelloWorld > HelloWorld
$ git add .
$ git commit -m "initial commit"
$ 
$ git checkout -b foo
$ 
$ git checkout master
$ echo ChangeInMaster > ChangeInMaster
$ git add .
$ git commit -m "change in master"
$ 
$ git checkout foo
$ echo ChangeInFoo > changeInFoo
$ git add .
$ git commit -m "change in foo"
$ 
$ git diff master
diff --git a/ChangeInFoo b/ChangeInFoo
new file mode 100644
index 0000000..7e38b29
--- /dev/null
+++ b/ChangeInFoo
@@ -0,0 +1 @@
+ChangeInFoo
diff --git a/ChangeInMaster b/ChangeInMaster
deleted file mode 100644
index f284658..0000000
--- a/ChangeInMaster
+++ /dev/null
@@ -1 +0,0 @@
-ChangeInMaster
$
$ git diff master...foo
diff --git a/ChangeInFoo b/ChangeInFoo
new file mode 100644
index 0000000..7e38b29
--- /dev/null
+++ b/ChangeInFoo
@@ -0,0 +1 @@
+ChangeInFoo
```

**Comment by rnveach** [comment]
Tests were added
