### ISSUE TITLE
Discuss components involved in regression

### ISSUE THREAD

**Issue by rnveach** [checkstyle/regression-tool#2]
Discuss and agree on all components project should have at a high level.

By PR, we currently have Git and Generator.

**Comment by rnveach** [comment]
I agree with git component.

Should we have `checkstyle` component?
We need to identify the type of file to restrict to only modules (for now). In the future, we also need to identify if the module has new/removed properties as they will need to be included in the regression.

I think we should rename `generator` to `configuration` as it will be clearer what we are doing in the package, creating the configuration(s).

We will need `report` component, which runs the configuration(s) and pushes the reports to a server.

IMO, each component should be completely isolated. We should have an extra package `data` that will be used to pass data between all the components.

**Comment by Luolc** [comment]
For `module` component. I agree with the functions you listed. But as pointed at https://github.com/checkstyle/regression-tool/pull/1#pullrequestreview-42136513. The method was not a good implementation, for it just instantiate the class for the release version of checkstyle, and that is meaningless. I haven't think out a way to load the class from file and meanwhile avoid conflicts by now. Should we discuss it here or create new issue? 

> I think we should rename generator to configuration as it will be clearer what we are doing in the package

I am OK with it.

> We will need report component, which runs the configuration(s) and pushes the reports to a server.

OK. Should we reuse the existing code in contribution repo?

**Comment by rnveach** [comment]
> Should we discuss it here or create new issue?

Create new issue, this discussion is for only high level information. Specifics will be done in specific issue for each component.
If we agree on high level details for each component, than create a new issue for all of them except the `data` package.
Put in all your specifics, questions, issues, and we will discuss things further.

> Should we reuse the existing code in contribution repo?

Be more specific, I assume you mean the regression groovy scripts? If so, than yes, we should try to re-use them.
We need a good reason not to be able to use them as they are widely used now.

**Comment by Luolc** [comment]
I am thinking about the filter. In git component there would be filters depending on path and changed type. But we may need some other filter, i.e. filter to judge whether it is a checkstyle modole. So we might need filters in `configuration` module as well. What's your option?

**Comment by rnveach** [comment]
IMO, filtering based on module should be in `module` component. `git` shouldn't be trying to dedude checkstyle modules as that puts too much work into the one module.
`configuration` should be given only the information it needs to create the configuration(s). So all the filtering should be done by then.

**Comment by Luolc** [comment]
@rnveach 
I agree that `git` component shouldn't do too many things. So `configuration` component is only to get data and use them to generate config; `module` component contains specific strategies. Is that right?

**Comment by rnveach** [comment]
> Is that right?

Yes, that is correct.

> contains specific strategies

I assume you mean based on default module, module with specific properties, etc.? Then yes.
We should always do all strategies, but for now we can start with the easiest.

**Comment by Luolc** [comment]
@rnveach I think I have no questions now. We would have `git`, `module`, `configuration` and `data`.

**Comment by rnveach** [comment]
> We would have git, module, configuration and data.

And `report`. :)
Than please start the issues.

**Comment by Luolc** [comment]
@rnveach Done. #19 , #20 , #21

**Comment by romani** [comment]
> We will need report component, which runs the configuration(s) and pushes the reports to a server.

please make `publish to` and `generation of reports` as separate steps/modules. Most of the time it will be used without publish as it might become our new standard of testing tool.

**Comment by rnveach** [comment]
> publish ... reports as separate steps/modules

All modules will be isolated except for their inputs and outputs.
Discussion of arguments to execute different areas will be at https://github.com/checkstyle/regression-tool/issues/32 . Right now we are focusing on creating the components.
