### ISSUE TITLE
Configuration Component

### ISSUE THREAD

**Issue by Luolc** [checkstyle/regression-tool#20]
Taken from #2 
`configuration` should be given only the information it needs to create the configuration(s). This would be the list of modules and the specified properties.

**Comment by rnveach** [comment]
@Luolc The following issue in Checkstyle must be completed for us to continue with 1 configuration with all modules: https://github.com/checkstyle/checkstyle/issues/4607

**Comment by Luolc** [comment]
@rnveach OK. I am looking on that.

**Comment by rnveach** [comment]
Issue is in our repo is done but we must finish issue in Checkstyle (https://github.com/checkstyle/checkstyle/issues/4607). I will leave this open to remind us of this.

**Comment by rnveach** [comment]
Fix in checkstyle was merged.
