### ISSUE TITLE
GitChange should be moved to data package

### ISSUE THREAD

**Issue by rnveach** [checkstyle/regression-tool#24]
https://github.com/checkstyle/regression-tool/blob/4edeee4de35edfeb48bdc030ea1d0d0d93e834ab/src/main/java/com/github/checkstyle/regression/git/GitChange.java

Data passed between components should be located in the `data` package.
They should be simple POJOs, with `final` fields, and try to avoid special classes like jgit.
It should be rare to update the import control for this package.

**Comment by Luolc** [comment]
Taken from the discussion in https://github.com/checkstyle/regression-tool/pull/22#pullrequestreview-43498710:
There is a question that whether we should expand a `ChangeType` field in `GitChange` in production code. Not regrading test code, I think that depends on whether we would treat the changes the same way or different way in config generators. Expect for `DELETE` (the file is gone), should we just not care about whether it is a new file or a modified file? By now the default config generator does not care about it.

**Comment by rnveach** [comment]
> Should we only focus on moving GitChange to data package without other changes in this issue?

Yes, this issue should only be us moving the class and not adding more fields.
We still have no need for the type of change in any other production code right now.

**Comment by rnveach** [comment]
Change was merged.
