### ISSUE TITLE
handle the tracking of deleted changes

### ISSUE THREAD

**Issue by Luolc** [checkstyle/regression-tool#25]
Taken from https://github.com/checkstyle/regression-tool/pull/22#pullrequestreview-43713402

The `newPath` of deleted file is always `/dev/null` as mentioned at https://github.com/eclipse/jgit/blob/005e5feb4ecd08c4e4d141a38b9e7942accb3212/org.eclipse.jgit/src/org/eclipse/jgit/diff/DiffEntry.java#L373.
These could also reflected in our test https://github.com/Luolc/regression-tool/blob/c5d69e8a780fa84e7b414641f263e01e18a11f45/src/test/java/com/github/checkstyle/regression/git/DiffParserTest.java#L87.

In the early discussion I want to keep "src/test" and deleted files mainly because I thought it is better to keep the possibility of getting all the changes, and leave a filter interface to let the real strategy code do decide which type of changes to use.

But I am re-thinking to drop deleted files now. If we would treat "ADD" and "MODIFY" the same way, then there is no need to distinguish the ChangeType. And "DELETE" is for sure useless as the file is gone.

**Comment by rnveach** [comment]
> we would treat "ADD" and "MODIFY" the same way

I agree.

> "DELETE" is for sure useless as the file is gone.

The 2 important questions are what files are we tracking and what information can we grab from them on the specific change (add/delete/etc.).

For the type of files, we should be tracking modules, module tests, and utilities (anything not a module in production).
From modules, we need to know properties, messages, etc.
For module tests, we should be able to get some example property values.
For utilities, we need to work backwards from code that changed, to methods, to the modules involved if any.

If a module is deleted, there is nothing for us to test anymore. Module tests being deleted should be rare and there should be an accompanying additional tests. Utilities being deleted should be accompanied by changes in their respective modules or other utilities.

I don't see deletes helping us any. So I agree we should drop them in the `git` component.

**Comment by rnveach** [comment]
This issue is blocked by PR #22 .

**Comment by Luolc** [comment]
I am going to create a PR to drop DELETE changes in main code, then rebase this in #18 and update the DELETE related UTs.

**Comment by rnveach** [comment]
@Luolc Can you just include the DELETE related UT in this PR then?
I specified this was blocked by the other PR. If you are going to do this first, than include a simple UT to showcase please.

**Comment by Luolc** [comment]
@rnveach I reference the wrong number... No #18 , it should be #22 . #22 is small now. It is not hard to update it, and dropping DELETE in main code is not big change. So the steps are:
1. add dropping DELETE in main code and add a simple UT of it
2. in #22 , rebase and update DELETE related code

**Comment by rnveach** [comment]
You may work on this then.

**Comment by rnveach** [comment]
Fix was merged
