### ISSUE TITLE
Git component

### ISSUE THREAD

**Issue by rnveach** [checkstyle/regression-tool#3]
Taken from https://github.com/checkstyle/regression-tool/pull/1 ,

We need to analyze `git` repository for changes in new commits in PR branch.

Notes:
* We most ignore deleted files. Deleted checks and such can never be checked for changes as they are gone. Moved/Renamed files should stay to make sure there is no issue using them.
* We must only grab files from `src/main`. Any changes in tests/it should be ignored.

Should we also grab the contents of the changes? Will they be needed?

Restricting files further by type should be done elsewhere as we will have to look at class hierarchy and such.

**Comment by rnveach** [comment]
@Luolc Based on discussions in PR, we will not be dropping `src/main` or deleted files. We will try to pull them in for #5 .
Will Git component do anything else?

**Comment by Luolc** [comment]
@rnveach 
I agree with your comment at https://github.com/checkstyle/regression-tool/pull/17#pullrequestreview-43132180 that we would expends the fields in the future, including file path and changed lines.
From https://github.com/checkstyle/regression-tool/pull/17#issuecomment-307365616, 
> If you wish to separate this out more, than filtered files would be a parameter to this class.

Do you mean add some regex strings to this class? Would the filters only depend on path? I am not very sure.

The mainly missing thing is the changed lines in GitChange, and maybe we could add them when we implement a generator which need them.

**Comment by rnveach** [comment]
> mean add some regex strings to this class?

That or full paths, but lets wait on this until we see a specific need.
I can see filtering on path and change type. I still think deleted files won't give us any benfits, but we'll wait and see.

> maybe we could add them when we implement a generator which need them.

That sounds fine to me.

If you see nothing else to add to the core of the git component, than I think we can close this issue.

**Comment by Luolc** [comment]
@rnveach  I think it is OK to close the issue now.

**Comment by romani** [comment]
just a note:
please do not be crazy with changes detection, it is better to grow its ability to detect changes with ability to process it.

**Comment by rnveach** [comment]
> it is better to grow its ability to detect

That is how we are breaking things apart.
