### ISSUE TITLE
Main

### ISSUE THREAD

**Issue by rnveach** [checkstyle/regression-tool#32]
We need a main class that users will use to access and run 'regression-tool'.

It needs to take in custom parameters, validate the parameters, and use those values to execute the tool.
If any parameters are wrongly entered, we need to give an informative error message and exit with non-zero code.
If an exception happens in any component, we should rethrow it all the way up to the Main class and display it to the user.

What kind of parameters will we accept? Which are required, which can be optional, and what will be the default values of the optional ones?
We will need a type of help menu, to display to users the list of parameters and their brief descriptions and anything else they need to know to use them correctly.

Blocked by Issue #19, #20, #21 .

**Comment by Luolc** [comment]
Arguments we found by now:
- **repository path**: the path of the repository. Required.
- **branch name**: the name of the PR branch. Required.

More arguments are need in `report` component. Those would depend on the discussion in #21

**Comment by rnveach** [comment]
@Luolc Once we are finished with all components up to and including generating config, we need to start this.
@romani wants a simple test program that will generate configs for users.

Other components may take a back seat and we may start working on expanding what is getting placed into the generated config file.

**Comment by rnveach** [comment]
@Luolc Please start this.
Config generation only should be some type of special option. It should not be the default.

**Comment by Luolc** [comment]
@rnveach 
> Config generation only should be some type of special option.

Do you mean that we have two options: 1. generate config and report 2. only generate config ?

**Comment by rnveach** [comment]
> Do you mean that we have two options: 1. generate config and report 

1 should be the default as this will be the most common case when our utility is fully functional. Users shouldn't need to give an option to do this, it should be default.
Not doing report should be some kind of a special option like, `-dontGenerateReport` or `-stopAfterGenerateConfig`.
We are not a configuration generation tool, we are a full regression tool. So our default behavior should be just that.

**Comment by rnveach** [comment]
Issues have been created for remaining work, so I am closing this
