### ISSUE TITLE
Fix diff problems when parsing a branch behind master

### ISSUE THREAD

**Issue by Luolc** [checkstyle/regression-tool#45]
Taken from https://github.com/checkstyle/regression-tool/pull/22#issuecomment-307849787
If the PR branch hasn't rebased on the latest commits of master, the GitChange list would contain the files that changed in master but haven't been merged into PR branch yet. And these are not expected.

As mentioned at https://github.com/checkstyle/regression-tool/issues/18#issuecomment-312427445, `git diff master...<branch>` could work, but there is no directly implementation of it in JGit.
Now I find a synonymous command:
```bash
$ git diff $(git merge-base master <branch>)..<branch>
```
So we just need to implement `git merge-base master <branch>` and run the common diff command.
There is no directly `merge-base` command in JGit either, but it seems not hard to implement it by some workaround. Ref: https://stackoverflow.com/questions/26434452/how-is-a-merge-base-done-in-jgit

**Comment by rnveach** [comment]
@Luolc Is there a command in JGit to find a common ancestor between 2 commits?
When a PR branch is behind master, it is still based on a specific commit in master, it is just not the latest commit.
If we find the common ancestor, we would only need to get the differences between that commit and the head PR commit.

**Comment by Luolc** [comment]
I think there is no direct command in JGit to do that. In git CLI, it is `git merge-base`. But the `Git` class doesn't have a method `mergeBase`. But there could be some workaround to find the common ancestor, as I mentioned at the previous post.

**Comment by rnveach** [comment]
Fix was merged
