### ISSUE TITLE
Update documentation along with code changes

### ISSUE THREAD

**Issue by Luolc** [checkstyle/regression-tool#66]
https://github.com/checkstyle/regression-tool/pull/60#discussion_r130596943
https://github.com/checkstyle/regression-tool/pull/60#discussion_r130596740
https://github.com/checkstyle/regression-tool/pull/60#discussion_r130597286
https://github.com/checkstyle/regression-tool/pull/60#discussion_r130597286

We have to update both codes and documentation for these.

**Comment by rnveach** [comment]
Fix was merged
