### ISSUE TITLE
git: add line changes detection

### ISSUE THREAD

**Issue by Luolc** [checkstyle/regression-tool#77]
We need to update `GitChange`. Add a field to store the line numbers of the changed code.
And update `DiffParser` to let it be able to detect line changes.

**Comment by rnveach** [comment]
> the number of changed lines.

Why do we need the number of changed lines instead the line numbers that changed?
We will need exact line numbers for things like Issue #69 .

**Comment by Luolc** [comment]
> Why do we need the number of changed lines instead of the line numbers that changed?

My expression was wrong. I updated the first post.

**Comment by rnveach** [comment]
Fix was merged
